card_dict = {0: "(0) The Fool",
             1: "(1) The Magician",
             2: "(2) The High Priestess",
             3: "(3) The Empress",
             4: "(4) The Emperor",
             5: "(5) The Hierophant",
             6: "(6) The Lovers",
             7: "(7) The Chariot",
             8: "(8) Strength",
             9: "(9) The Hermit",
             10: "(10) Wheel of Fortune",
             11: "(11) Justice",
             12: "(12) The Hanged Man",
             13: "(13) Death",
             14: "(14) Temperance",
             15: "(15) The Devil",
             16: "(16) The Tower",
             17: "(17) The Star",
             18: "(18) The Moon",
             19: "(19) The Sun",
             20: "(20) Judgment",
             21: "(21) The World",
             22: "(22) Ace of Wands",
             23: "(23) Two of Wands",
             24: "(24) Three of Wands",
             25: "(25) Four of Wands",
             26: "(26) Five of Wands",
             27: "(27) Six of Wands",
             28: "(28) Seven of Wands",
             29: "(29) Eight of Wands",
             30: "(30) Nine of Wands",
             31: "(31) Ten of Wands",
             32: "(32) Page of Wands",
             33: "(33) Knight of Wands",
             34: "(34) King of Wands",
             35: "(35) Queen of Wands",
             36: "(36) Ace of Cups",
             37: "(37) Two of Cups",
             38: "(38) Three of Cups",
             39: "(39) Four of Cups",
             40: "(40) Five of Cups",
             41: "(41) Six of Cups",
             42: "(42) Seven of Cups",
             43: "(43) Eight of Cups",
             44: "(44) Nine of Cups",
             45: "(45) Ten of Cups",
             46: "(46) Page of Cups",
             47: "(47) Knight of Cups",
             48: "(48) King of Cups",
             49: "(49) Queen of Cups",
             50: "(50) Ace of Swords",
             51: "(51) Two of Swords",
             52: "(52) Three of Swords",
             53: "(53) Four of Swords",
             54: "(54) Five of Swords",
             55: "(55) Six of Swords",
             56: "(56) Seven of Swords",
             57: "(57) Eight of Swords",
             58: "(58) Nine of Swords",
             59: "(59) Ten of Swords",
             60: "(60) Page of Swords",
             61: "(61) Knight of Swords",
             62: "(62) King of Swords",
             63: "(63) Queen of Swords",
             64: "(64) Ace of Pentacles",
             65: "(65) Two of Pentacles",
             66: "(66) Three of Pentacles",
             67: "(67) Four of Pentacles",
             68: "(68) Five of Pentacles",
             69: "(69) Six of Pentacles",
             70: "(70) Seven of Pentacles",
             71: "(71) Eight of Pentacles",
             72: "(72) Nine of Pentacles",
             73: "(73) Ten of Pentacles",
             74: "(74) Page of Pentacles",
             75: "(75) Knight of Pentacles",
             76: "(76) King of Pentacles",
             77: "(77) Queen of Pentacles",
             }
